[log]
  level = "DEBUG"

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

# Force HTTPS
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"


